import Anthropic from "@anthropic-ai/sdk";
import type { ExtractedRecipe, GeneratedList, Ingredient, ListItem } from "@/types";

export interface RichExtractedRecipe extends ExtractedRecipe {
  tagline: string;
  effort_level: 'low' | 'med' | 'high';
  cook_time_minutes: number;
  cost_per_serving: number;
  steps: string[];
}

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

function stripCodeFences(text: string): string {
  return text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
}

export async function extractRecipe(
  transcript: string,
  sourceUrl: string
): Promise<ExtractedRecipe> {
  const response = await client.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 2048,
    messages: [
      {
        role: "user",
        content: `You are a recipe extraction assistant. Extract the recipe from this cooking video transcript.

The transcript was generated by speech-to-text and may contain mishearing errors — especially for ingredient names (e.g. "milky mushrooms" likely means "enoki mushrooms"). Use your culinary knowledge to correct any obvious transcription errors before extracting.

Transcript:
${transcript}

Return a JSON object with this exact shape:
{
  "title": "Recipe name",
  "ingredients": [
    { "name": "ingredient name", "quantity": "amount + unit", "notes": "optional prep notes" }
  ],
  "serves": 4
}

If no recipe is detectable, return: { "error": "No recipe found" }

Return only the JSON, no other text.`,
      },
    ],
  });

  const raw = response.content.find((b) => b.type === "text")?.text ?? "";
  const text = stripCodeFences(raw);

  let parsed: { title: string; ingredients: Ingredient[]; serves?: number; error?: string };
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error("Claude returned invalid JSON for recipe extraction");
  }

  if (parsed.error) {
    throw new Error(parsed.error);
  }

  return {
    title: parsed.title,
    ingredients: parsed.ingredients ?? [],
    serves: parsed.serves,
    sourceUrl,
  };
}

export async function extractRichRecipe(
  transcript: string,
  sourceUrl: string
): Promise<RichExtractedRecipe> {
  const response = await client.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 3000,
    messages: [
      {
        role: "user",
        content: `You are a recipe extraction assistant for a student cooking app. Extract the recipe from this cooking video transcript.

The transcript was generated by speech-to-text and may contain mishearing errors — use your culinary knowledge to correct them.

Transcript:
${transcript}

Return a JSON object with this exact shape:
{
  "title": "Recipe name",
  "tagline": "Short witty one-liner describing the vibe (e.g. 'Low effort. High reward.')",
  "effort_level": "low" | "med" | "high",
  "cook_time_minutes": 15,
  "cost_per_serving": 4.50,
  "ingredients": [
    { "name": "ingredient name", "quantity": "amount + unit", "notes": "optional prep notes", "flag": "swap" | "optional" | null, "swapSuggestion": "cheaper alternative (only if flag is swap, else omit)" }
  ],
  "steps": [
    "Step 1 description.",
    "Step 2 description."
  ],
  "serves": 2
}

Ingredient flag guide:
- "swap": exotic, expensive, or single-use ingredients — include a swapSuggestion with a cheaper/easier alternative
- "optional": nice-to-have but the dish works without it
- null: essential, everyday ingredient

Effort level guide:
- "low": under 15 min, 1 pot/pan, minimal skill
- "med": 15-30 min, 2+ pots/pans, some technique
- "high": 30+ min, multiple steps, more involved

Estimate cost_per_serving based on typical US grocery store prices.

If no recipe is detectable, return: { "error": "No recipe found" }

Return only the JSON, no other text.`,
      },
    ],
  });

  const raw = response.content.find((b) => b.type === "text")?.text ?? "";
  const text = stripCodeFences(raw);

  let parsed: {
    title: string;
    tagline: string;
    effort_level: 'low' | 'med' | 'high';
    cook_time_minutes: number;
    cost_per_serving: number;
    ingredients: Ingredient[];
    steps: string[];
    serves?: number;
    error?: string;
  };

  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error("Claude returned invalid JSON for recipe extraction");
  }

  if (parsed.error) {
    throw new Error(parsed.error);
  }

  return {
    title: parsed.title,
    tagline: parsed.tagline ?? "",
    effort_level: parsed.effort_level ?? "med",
    cook_time_minutes: parsed.cook_time_minutes ?? 20,
    cost_per_serving: parsed.cost_per_serving ?? 5,
    ingredients: parsed.ingredients ?? [],
    steps: parsed.steps ?? [],
    serves: parsed.serves,
    sourceUrl,
  };
}

export async function generateList(
  recipes: ExtractedRecipe[],
  budget: number
): Promise<GeneratedList> {
  const recipesText = recipes
    .map(
      (r, i) =>
        `Recipe ${i + 1}: ${r.title}\nIngredients:\n${r.ingredients
          .map((ing) => `  - ${ing.quantity} ${ing.name}${ing.notes ? ` (${ing.notes})` : ""}`)
          .join("\n")}`
    )
    .join("\n\n");

  const response = await client.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 4096,
    messages: [
      {
        role: "user",
        content: `You are a smart grocery list generator for college students. The user has a weekly grocery budget of $${budget}.

Here are the recipes they want to make:

${recipesText}

Create a consolidated shopping list. Return a JSON object with this exact shape:
{
  "items": [
    {
      "name": "ingredient name",
      "quantity": "amount + unit",
      "estimatedCost": 3.99,
      "flag": "swap" | "optional" | null,
      "swapSuggestion": "cheaper alternative (only if flag is swap)"
    }
  ],
  "totalEstimate": 45.50,
  "overBudget": false,
  "budgetNotes": "Brief note about budget fit, or top 2-3 swap suggestions if over budget"
}

Rules:
- Consolidate duplicate ingredients across recipes
- Flag "swap" for exotic, single-use, or expensive ingredients with cheaper alternatives
- Flag "optional" for nice-to-have but not essential ingredients
- Use realistic Wegmans/Tops/grocery store pricing
- If total exceeds $${budget}, set overBudget to true and identify substitutions in budgetNotes

Return only the JSON, no other text.`,
      },
    ],
  });

  const raw = response.content.find((b) => b.type === "text")?.text ?? "";
  const text = stripCodeFences(raw);

  let parsed: { items: Omit<ListItem, "checked">[]; totalEstimate: number; overBudget: boolean; budgetNotes: string };
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error("Claude returned invalid JSON for list generation");
  }

  return {
    items: (parsed.items ?? []).map((item: Omit<ListItem, "checked">): ListItem => ({
      ...item,
      checked: false,
    })),
    totalEstimate: parsed.totalEstimate ?? 0,
    overBudget: parsed.overBudget ?? false,
    budgetNotes: parsed.budgetNotes ?? "",
  };
}
